### PR TITLE
Add gcov-symlinks to the SDK task

### PR DESCRIPTION
**Pull request by ebassi**
Yocto builds gcov and gcov-tool and names them using the target platform.
This is to allow cross-compilation for a target platform, in order to do code
coverage tests on devices, take the files out, and run the reporting tools on
the development machine.

In order to have the more user- and script-friendly names, we need to build
the `gcov-symlinks` recipe as well.

### CODE REVIEW

**Comment by albfan** [comment]
How is this supposed to get reflected on dependent runtimes? I did:

    $ flatpak update org.gnome.Sdk

And still there's no gcov avaliable

**Comment by albfan** [comment]
Just see ae698d669679935005d149de49b751b3271762ac. No chances then? Any related info?

**Comment by alexlarsson** [comment]
We just need a better fux

**Comment by alexlarsson** [comment]
Fix

**Comment by albfan** [comment]
But what is the problem:

```
$ flatpak-builder --run dist <any-flatpak-manifest> sh
sh-4.3$ find /usr -name *gcov*
/usr/bin/x86_64-unknown-linux-gcov
/usr/bin/x86_64-unknown-linux-gcov-tool
/usr/lib/x86_64-unknown-linux/6.2.0/libgcov.a
sh-4.3$ 
```

`/usr/bin/x86_64-unknown-linux-gcov` is there, just need a symlink to`/usr/bin/gcov`

**Comment by ebassi** [comment]
@albfan The problem is that the Yocto recipe that adds those symlinks, `gcov-symlinks`, does not get resolved correctly and breaks the build. Alex reverted my commit to keep the SDK building.

There's a commit sent to the OpenEmbedded mailing list for review [this March](https://patchwork.openembedded.org/patch/138023/) that adds those symlinks as part of the installation recipe. This requires an ad hoc patched recipe, which would make the rebasing of the SDK on Yocto harder.

**Comment by albfan** [comment]
Ah ok. I'm using gcov from system so this fix is not really urgent for me. Hope it gets resolved soon

**Comment by alexlarsson** [comment]
I backported the fix from yocto master, so next build should get this.

**Pull request merged**
